### ISSUE TITLE
Android: Unable to update properties for view tag xxx

### ISSUE THREAD

**Issue by wendan52** [archriss/react-native-snap-carousel#234]
logcat print this:
```
E/NativeViewHierarchyManager:Unable to update properties for view tag 875
                              com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 875 could not be found
                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:123)
                                  at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:240)
                                  at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
                                  at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:497)
                                  at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:408)
                                  at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:126)
                                  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)
                                  at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                  at android.view.Choreographer.doFrame(Choreographer.java:616)
                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                  at android.os.Handler.handleCallback(Handler.java:751)
                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                  at android.os.Looper.loop(Looper.java:154)
                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                  at java.lang.reflect.Method.invoke(Native Method)
                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

my code is:
```
<Carousel
          slideStyle={{ flex: 1 }}
          sliderWidth={screenWidth}
          itemWidth={itemWidth}
          data={headImages}
          renderItem={this._renderCarouselItem}
          firstItem={0}
          inactiveSlideScale={0.94}
          inactiveSlideOpacity={0.6}
          containerCustomStyle={styles.slider}
          contentContainerCustomStyle={styles.sliderContainer}
          showsHorizontalScrollIndicator={false}
          snapOnAndroid={true}
          removeClippedSubviews={false} />
```

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**
