### ISSUE TITLE
Getting error while swiping the cards in android

### ISSUE THREAD

**Issue by john1jan** [archriss/react-native-snap-carousel#269]
```
Unable to update properties for view tag 1369
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1369 could not be found
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:123)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:240)
        at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
        at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:497)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:368)
        at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:119)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEvent(ReactScrollViewHelper.java:60)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEvent(ReactScrollViewHelper.java:33)
        at com.facebook.react.views.scroll.ReactHorizontalScrollView.onScrollChanged(ReactHorizontalScrollView.java:120)
        at android.view.View.scrollTo(View.java:13539)
        at android.widget.HorizontalScrollView.onOverScrolled(HorizontalScrollView.java:774)
        at android.view.View.overScrollBy(View.java:21493)
        at android.widget.HorizontalScrollView.onTouchEvent(HorizontalScrollView.java:626)
        at com.facebook.react.views.scroll.ReactHorizontalScrollView.onTouchEvent(ReactHorizontalScrollView.java:155)
        at android.view.View.dispatchTouchEvent(View.java:10149)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2742)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2371)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2748)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
                                                                                            
```

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**
