### ISSUE TITLE
lib crashes when running it with existing native app

### ISSUE THREAD

**Issue by matyj** [archriss/react-native-snap-carousel#298]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android 6, 7, 8

### Is the bug reproductible in a production environment (not a debug one)?

Only in production

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

No

### Environment

  Environment:
"react": "16.2.0",
"react-native": "0.52.1",
"react-native-snap-carousel": "^3.6.0",

Target Platform:
    Android (6.0, 7.0, 8.0)
    iOS (10.3)

### Steps to Reproduce

1. The react native app which uses this lib is integrated with existing native app.
2. After running the native app with "react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output ../app/src/main/assets/index.android.bundle --assets-dest ../app/src/main/res/" called before crash happpens.

### Expected Behavior

There should be no crash.

### Actual Behavior

Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'a.constructor')

This error is located at:
    in r
    in RCTView
    in RCTView
    in t, stack:
prepareFlow@303:621
value@303:1002
u@41:76348
beginWork@41:78181
n@41:104147
i@41:104488
o@41:104834
k@41:109010
C@41:108553
v@41:107780
p@41:107062
d@41:106750
t@41:61874
updateContainer@41:123554
render@41:69172
exports@280:730
run@276:615
runApplication@276:2046
value@18:3582
<unknown>@18:1067
value@18:3009
value@18:1039

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:764)

**Comment by bd-arc** [comment]
Hi @matyj,

I genuinely don't see how to help you. There is no way for me to reproduce your issue and there is nothing that clearly links it to the plugin...
