### ISSUE TITLE
App crashes-After updating to 60.5(Crash happen when swipe left to right)

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [archriss/react-native-snap-carousel#591]
E/ReactNativeJS: Can't find variable: _this
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.unlimited_movies_in_com, PID: 13264
    com.facebook.react.common.JavascriptException: Can't find variable: _this, stack:
    onMomentumScrollEnd@255:7008
    E@82:1233
    z@82:1376
    U@82:1430
    D@82:1721
    H@82:2497
    j@82:2312
    <unknown>@82:13831
    Ue@82:81479
    Me@82:13499
    Fe@82:13672
    receiveEvent@82:14058
    value@23:3518
    <unknown>@23:822
    value@23:2772
    value@23:794
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
