### ISSUE TITLE
Proper unit testing for Carousel component

### ISSUE THREAD

**Issue by leonie-koch** [archriss/react-native-snap-carousel#848]
### Is this a bug report, a feature request, or a question?

question

### Expected Behavior

I would like to properly test my component with react-native-snap-carousel with jest. I already tested a lot with mocking the component somehow, but as I am beginner to react I couldn't figure out a way, also didn't find any working solution after spending long time searching issues on github and stackoverflow. Is there a best practice to do unit tests with react-native-snap-carousel und jest?

### Actual Behavior

I got the following error:

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/leoniekoch/Desktop/N-Fototester-Native/node_modules/react-native-snap-carousel/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Carousel from './carousel/Carousel';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      10 |   Text,
      11 | } from '@ui-kitten/components';
    > 12 | import Carousel, {ParallaxImage} from 'react-native-snap-carousel';
         | ^
      13 |
      14 | const GLOBAL = require('./components/constants');
      15 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (screens/Tutorial1.js:12:1)
```

### Steps to Reproduce

1. npm install react native
2. created the following testfile
3. ran npm test

Tutorial-test.js

```
import 'react-native';
import React from 'react';
import {Tutorial1} from '../screens/Tutorial1';
import * as eva from '@eva-design/eva';
import {EvaIconsPack} from '@ui-kitten/eva-icons';
import {ApplicationProvider, IconRegistry} from '@ui-kitten/components';
import renderer from 'react-test-renderer';
jest.useFakeTimers();
jest.mock('@react-navigation/native');

it('renders correctly', () => {
  const tree = renderer
    .create(
      <>
        <IconRegistry icons={EvaIconsPack} />
        <ApplicationProvider {...eva} theme={eva.light}>
          <Tutorial1 />
        </ApplicationProvider>
      </>,
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});
```
my jest config file

```
const config = {
  verbose: true,
  preset: 'react-native',
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|react-native-snap-carousel)/)',
  ],
};

module.exports = config;

```

Thanks for helping!!

**Comment by sizhe-eb** [comment]
Is there any solution? I'm also facing this issue. I just used `Pagination`.

**Comment by riamon-v** [comment]
> Is there any solution? I'm also facing this issue. I just used `Pagination`.

Same here, jsute using Pagination and getting this errors while testing
